language: ruby
rvm:
  - 2.1.1

before_install:
  - echo $TRAVIS_COMMIT_RANGE
    # Copy proselint settings to home.
  - cp .proselintrc ~/

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site
  - bundle exec danger

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
